### ISSUE TITLE
Typo in the basic files

### ISSUE THREAD

**Issue by jsherman91** [fengqzHD/gmIdNeoKit#1]
In the techsweep_config_bsim4_XXX_tech_spectre.m file, the netlist on line 107 has the term 'rawfile = "./%s.raw [...]'. The .raw should be removed as the c.outfile includes the .raw file, and when calling cds_srr later, it calls it from c.outfile, not c.outfile.raw.

**Comment by fengqzHD** [comment]
You are totally correct. I removed the raw in the netlist creation part in the last time I used the tool. I will fix this and close the issue.
