### ISSUE TITLE
More Model Files 

### ISSUE THREAD

**Issue by wgtLencha** [fengqzHD/gmIdNeoKit#2]
Here are my questions:
From your techSw_config_bsim3_180msr_spectre.m file:
Line # 22: 
c.modelfile = sprintf('"/tech/tsmc/tsmc180/tsmc180_fengqz_flybackv1/tsmc180/models/spectre/rf018.scs" section=%s', c.corner);
Is that the location of the model file?
What if I have more than one model files? Do I have to repeat the command line? For Example,
c.modelfile = sprintf('"/GF8HP/models/spectre/design.scs" section=%s', c.corner);
c.modelfile = sprintf('"/GF8HP/models/spectre/wafer.scs" section=%s', c.corner);
c.modelfile = sprintf('"/GF8HP/models/spectre/allModels.scs" section=%s', c.corner);

Line # 29: 
c.simcmd = 'spectre -64 techsweep_180msrf.scs +log techsweep_180msrf.out';
That is the name you are giving to the spectre output file?

Line # 30: 
c.outfile = 'techsweep_180msrf.raw';
Is the name of the output file?

In my case what I have done is as follows:
I created a test bench in Cadence virtuoso ADE XL separately for each MOS transistors with ideal DC voltage sources and created the testbench so that it matches  the following netlisting for example for NMOS. And I repeated the same step for PMOS transistor.
 vnoi     (vx  0)         vsource dc=0  \n'...
'vdsn     (vdn vx)        vsource dc=ds  \n'...
'vgsn     (vgn 0)         vsource dc=gs  \n'...
'vbsn     (vbn 0)         vsource dc=-sb \n'...

Then I swept the channel length and did a parametric sweep of vds, vgs, and vsb. Once the simulation finishes, I provided the psf path in my techsweep_config file by doing:
c.outfile = ‘/home/users/simulation/techsweep_config_psp_120nm_nmos_spectre/adexl/results/data/pmos_ch/psf/pmos_charct/psf’;
For both PMOS and NMOS transistors separately.
Any feedback will be appreciated.
Thanks a lot

**Comment by fengqzHD** [comment]
Line # 22
The model specified in this line is included in the output netlist. (techsweep_180msrf.scs in the sample file). You can see that clearly from Line # 102 to Line # 134 especially Line # 104 and Line # 127. If you want to include more models, you have to define more models and insert them into the output netlist. 
For example
In Line # 22
c.modelfile0 = sprintf('"/GF8HP/models/spectre/design.scs" section=%s', c.corner);
c.modelfile1 = sprintf('"/GF8HP/models/spectre/wafer.scs" section=%s', c.corner);
c.modelfile2 = sprintf('"/GF8HP/models/spectre/allModels.scs" section=%s', c.corner);

In Line # 104
'include  %s\n'...
'include  %s\n'...
'include  %s\n'...

In Line # 127
], c.modelfile0, c.modelfile1,  c.modelfile2, ...

**Comment by fengqzHD** [comment]
As for your questions about Line # 29 and Line # 30, you don't need to set the output path to the psf folder from ADE XL.

Based on my limited understanding, once you run techSw_spectre_run in Matlab. Matlab would start the simulation in spectre using the command in Line # 29. Then the data would be collected by a Matlab function cds_srr. You can find more about how the data is generated in Prof. Murmann's book and read the script of techSw_spectre_run.m.

**Comment by wgtLencha** [comment]
Hello,
Thanks for your quick prompt.  I run the techsweep_spectre_run in Matlab and got the following error:Loading /apps/cds/spectre191/tools.lnx86/cmi/lib/64bit/5.0/libinfineon_sh.so ...
Loading /apps/cds/spectre191/tools.lnx86/cmi/lib/64bit/5.0/libphilips_o_sh.so ...
Loading /apps/cds/spectre191/tools.lnx86/cmi/lib/64bit/5.0/libphilips_sh.so ...
Loading /apps/cds/spectre191/tools.lnx86/cmi/lib/64bit/5.0/libsparam_sh.so ...
Loading /apps/cds/spectre191/tools.lnx86/cmi/lib/64bit/5.0/libstmodels_sh.so ...
Reading file:  /home/UFAD/wako/GF8HP/techsweep_120psp.scs
Reading file:  /apps/cds/spectre191/tools.lnx86/spectre/etc/configs/spectre.cfg

Error found by spectre during circuit read-in.
    ERROR (SFE-874): "techsweep_120psp.scs" 2: 10: Unexpected operator "/". Cannot run the simulation because of syntax error. Correct the error and rerun the simulation.
Warning from spectre during circuit read-in.
    WARNING (SFE-3266): "techsweep_120psp.scs" 2: The first line is treated as a comment following Spice convention. Check the netlist to ensure that the valid content does not start from the first line.
Error found by spectre during circuit read-in.
    ERROR (SFE-874): "techsweep_120psp.scs" 3: 10: Unexpected operator "/". Cannot run the simulation because of syntax error. Correct the error and rerun the simulation.
    ERROR (SFE-874): "techsweep_120psp.scs" 4: 10: Unexpected operator "/". Cannot run the simulation because of syntax error. Correct the error and rerun the simulation.

Reading file:  /home/UFAD/wako/GF8HP/techsweep_params_120psp.scs
Time for NDB Parsing: CPU = 58.299 ms, elapsed = 81.66 ms.
Time accumulated: CPU = 76.645 ms, elapsed = 81.6629 ms.
Peak resident memory used = 57.7 Mbytes.

**Comment by wgtLencha** [comment]
Here are my techsweep_config_psp_120_spectre.m and techsweep_spectre_run.m files 

[techsweep_config_psp_120_spectre.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4196111/techsweep_config_psp_120_spectre.txt)
[techsweep_spectre_run.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4196112/techsweep_spectre_run.txt)

**Comment by fengqzHD** [comment]
Given that the error is a syntax error of the netlist, it would be helpful if we could get a working netlist first to debug the error. I would check the netlist generated in ADE and compare that to the one generated by the config file as I am not sure what is the syntax error.

**Comment by wgtLencha** [comment]
After making a few corrections. It has run and generated a netlist file and I have compared the netlist file generated by the config file and ADE. I am observing something interesting. 
sweepvds sweep param=ds start=0 stop=4.000000e-01 step=1.200000e+00 { 
   sweepvgs dc param=gs start=0 stop=4.000000e-01 step=1.200000e+00 
Indread of getting for vds start=0 stop=1.2 step=0.4 and for vgs start=0 stop=1.2 step=0.4
I will attach the netlist files. 
1. generated by config//techsweep_120psp.scs 
include "/grps/ef-test/GF8HP/Models/Spectre/models/design.scs" 
include "/grps/ef-test/GF8HP/Models/Spectre/models/wafer.scs" 
include ""/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt" 
include "techsweep_params_120psp.scs" 
save mn 
save mp 
parameters gs=0 ds=0 
vnoi     (vx  0)         vsource dc=0  
vdsn     (vdn vx)        vsource dc=ds  
vgsn     (vgn 0)         vsource dc=gs  
vbsn     (vbn 0)         vsource dc=-sb 
vdsp     (vdp vx)        vsource dc=-ds 
vgsp     (vgp 0)         vsource dc=-gs 
vbsp     (vbp 0)         vsource dc=sb  

mn       (vdn vgn 0 vbn) nch  l=length*1e-6 w=10e-6 m=5 
mp       (vdp vgp 0 vbp) pch  l=length*1e-6 w=10e-6 m=5 

simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=27 tnom=27 rawfmt=psfbin rawfile="./1.200000e+00" 
sweepvds sweep param=ds start=0 stop=4.000000e-01 step=1.200000e+00 { 
   sweepvgs dc param=gs start=0 stop=4.000000e-01 step=1.200000e+00 
}
sweepvds_noise sweep param=ds start=0 stop=4.000000e-01 step=1.200000e+00 { 
   sweepvgs_noise noise freq=1 oprobe=vnoi param=gs start=0 stop=4.000000e-01 step=
2. Generated by ADE manually:
// Point Netlist Generated on: Feb 12 14:19:18 2020
// Generated for: spectre
// Design Netlist Generated on: Feb 12 14:19:18 2020
// Design library name: characterization
// Design cell name: techsweep_config_psp_120nm_pmos_spectre
// Design view name: schematic
simulator lang=spectre
global 0
parameters ds=0 gs=0 length=0.12u sb=0
include "design.scs"
include "wafer.scs"
include "allModels.scs" section=tt
include "/home/UFAD/GF8HP/savemp.scs"

// Library name: characterization
// Cell name: techsweep_config_psp_120nm_pmos_spectre
// View name: schematic
mp (vdp vgp 0 vbp) pfet l=length w=10u nf=5 m=1 par=(1) ngcon=1 \
        ad=1.434625e-13 as=1.434625e-13 pd=2.61u ps=2.61u nrd=0.313 \
        nrs=0.313 rf_rsub=1 plnest=-1 plorient=-1 pld200=-1 pwd100=-1 \
        lstis=1 lnws=0 panw1=0 panw2=0 panw3=0 panw4=0 panw5=0p panw6=0 \
        panw7=0 panw8=0 panw9=0 panw10=0 sa=5.5e-07 sb=5.5e-07 sd=3.6e-07 \
        dtemp=0.0 p_vta=0
vnoi (vx 0) vsource dc=0 type=dc
vbsp (vbp 0) vsource dc=sb type=dc
vdsp (vdp vx) vsource dc=-ds type=dc
vgsp (vgp 0) vsource dc=-gs type=dc
simulatorOptions options psfversion="1.1.0" reltol=1e-3 vabstol=1e-6 \
    iabstol=1e-12 temp=27 tnom=25 scalem=1.0 scale=1.0 gmin=1e-12 rforce=1 \
    maxnotes=5 maxwarns=5 digits=5 cols=80 pivrel=1e-3 \
    sensfile="../psf/sens.output" checklimitdest=psf 
dcOp dc write="spectre.dc" maxiters=150 maxsteps=10000 annotate=status
dcOpInfo info what=oppoint where=rawfile
dc dc param=length start=0.2u stop=2u step=0.25u values=[0.12u] \
    oppoint=rawfile maxiters=150 maxsteps=10000 annotate=status
modelParameter info what=models where=rawfile
element info what=inst where=rawfile
outputParameter info what=output where=rawfile
designParamVals info what=parameters where=rawfile
primitives info what=primitives where=rawfile
subckts info what=subckts where=rawfile
saveOptions options save=selected currents=selected

**Comment by wgtLencha** [comment]
The error is still there. I have tested my spectre and created a simple spectre file and run it from the command line and it works.  Here is the simple spectre code with the same technology files.// Resistively loaded common Source Amplifier 
simulator lang=spectre
* model files
* include "/grps/ef-test/GF8HP/Models/Spectre/modelsModels/Spectre/models"
include "/grps/ef-test/GF8HP/Models/Spectre/models/design.scs"
include "/grps/ef-test/GF8HP/Models/Spectre/models/wafer.scs"
include "/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt
model nch psp103 type=n
* save results
save mn
* Assiging Parameters
parameters vds=1.2 vgs=0.6 ibias=50u vsb=0

*Scheamtic descriptions

vdsn (vdn 0) vsource dc=vds
vgsn (vgn 0) vsource dc=vgs mag=1
vbsn (vbn 0) vsource dc=-vsb
mn (vo vgn 0 vbn) nch l=0.12u w=10u
ib (vdn vo) isource dc=ibias
r1 (vdn vo) resistor r=1.4k
c1 (vo 0) capacitor c=2p

* Defining options
options1 options gmin=0.1p reltol=0.1m vabstol=1u iabstol=100p
options2 options temp=27 tnom=27
options3 options save=allpub rawfmt=psfbin rawfile="./cs.raw"

* Start simulations
dc1 dc param=vgs start=0 stop=1.2 step=1m
ac1 ac start=100k stop=1G dec=100
noise1 (vo,0) noise start=100k stop=1T dec=100

**Comment by fengqzHD** [comment]
I don't think the difference in the sweep section may cause the syntax error.

One thing I notice is this one
_include ""/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt"_

I think it should be
_include "/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt_

**Comment by wgtLencha** [comment]
Thanks. I changed model files in the Matlabconfig as follows:c.modelfile1 = sprintf('/grps/ef-test/GF8HP/Models/Spectre/models/design.scs');
c.modelfile2 = sprintf('/grps/ef-test/GF8HP/Models/Spectre/models/wafer.scs');
and in the netlist I added:
'include "/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt \n'...
It ran and in the log file It generated an error that says:
[log.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4196618/log.txt)
ERROR (SFE-874): "techsweep_120psp.scs" 25: 82: Unexpected end of file "". Cannot run the simulation because of syntax error. Correct the error and rerun the simulation. I am attaching the log file.
[log.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4196621/log.txt)
From looking at the error message, I see that my netlist file end at line #25 gets clipped.
Here is my netlist generated from the config file
//techsweep_120psp.scs 
include "/grps/ef-test/GF8HP/Models/Spectre/models/design.scs" 
include "/grps/ef-test/GF8HP/Models/Spectre/models/wafer.scs" 
include "/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt 
include "techsweep_params_120psp.scs" 
save mn 
save mp 
parameters gs=0 ds=0 
vnoi     (vx  0)         vsource dc=0  
vdsn     (vdn vx)        vsource dc=ds  
vgsn     (vgn 0)         vsource dc=gs  
vbsn     (vbn 0)         vsource dc=-sb 
vdsp     (vdp vx)        vsource dc=-ds 
vgsp     (vgp 0)         vsource dc=-gs 
vbsp     (vbp 0)         vsource dc=sb  

mn       (vdn vgn 0 vbn) nch  l=length*1e-6 w=10e-6 m=5 
mp       (vdp vgp 0 vbp) pch  l=length*1e-6 w=10e-6 m=5 

simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=27 tnom=27 rawfmt=psfbin rawfile="./1.200000e+00" 
sweepvds sweep param=ds start=0 stop=4.000000e-01 step=1.200000e+00 { 
   sweepvgs dc param=gs start=0 stop=4.000000e-01 step=1.200000e+00 
}
sweepvds_noise sweep param=ds start=0 stop=4.000000e-01 step=1.200000e+00 { 
   sweepvgs_noise noise freq=1 oprobe=vnoi param=gs start=0 stop=4.000000e-01 step=

**Comment by wgtLencha** [comment]
Hello,
Now the simulation runs when I added the following line in the simulation netlist section
'include "/grps/ef-test/GF8HP/Models/Spectre/models/allModels.scs" section=tt \n'...
And line # 120 of your techSw_config_bsim3_180msrf_spectre Matlab file has a  rawfile="./%s" \n'...
 'simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=%d tnom=27 rawfmt=psfbin rawfile="./%s" \n'...
Which I modified as follows:
'simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=%d tnom=27 rawfmt=psfbin rawfile="./techsweep_120psp.raw" \n'...
Then the simulation ran. Here are my simulation logfiles: The first one is the run log and the second one is the final log.
[sim_log.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4198241/sim_log.txt)
[log_file.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4198242/log_file.txt)
But I am getting the following error with regard to cds_srr
techsweep_spectre_run
Simulation Starts for L = 0.120
Simulation Finished for L = 0.120 with VSB = 1.00 V
Info, results techsweep_120psp.raw are changed, reloading
Error: The special signal is not exist.
One or more output arguments not assigned during call to "cds_innersrr".

Error in cds_srr (line 20)
  sig = cds_innersrr(dirname, dataset, signame, verbose);

Error in techsweep_spectre_run (line 66)
            struct_n = cds_srr(c.outfile, c.sweep, params_n{1});
But when I do 
cds_srr(c.outfile, c.sweep), I get some data as follows:Total: 40 properties
	 'PSFversion' 	 'BINPSF creation time' 	 'ENV_VAR_0' 	 'ENV_VAR_1' 	 'ENV_VAR_2' 	 'ENV_VAR_3' 	 'ENV_VAR_4' 	 'ENV_VAR_5' 	 'ENV_VAR_6' 	 'ENV_VAR_7' 	 'ENV_VAR_8' 	 'ENV_VAR_9' 	 'ENV_VAR_10' 	 'ENV_VAR_11' 	 'ENV_VAR_12' 	 'ENV_VAR_13' 	 'PSF style' 	 'PSF types' 	 'PSF sweeps' 	 'PSF sweep points' 	 'PSF sweep min' 	 'PSF sweep max' 	 'PSF groups' 	 'PSF traces' 	 'simulator' 	 'version' 	 'date' 	 'design' 	 'analysis type' 	 'analysis name' 	 'analysis description' 	 'xVecSorted' 	 'tolerance.relative' 	 'reltol' 	 'abstol(V)' 	 'abstol(I)' 	 'temp' 	 'tnom' 	 'tempeffects' 	 'gmindc' 

Total: 18 type(s) of signals
Signal type: V	Data type: Real
	 'mn:vds' 	 'mn:vgs' 	 'mn:vsb' 	 'mn:vto' 	 'mn:vts' 	 'mn:vth' 	 'mn:vgt' 	 'mn:vdss' 	 'mn:vearly' 	 'mn:lp_vfb' 	 'mn:lp_a2' 	 'mn:vbs' 	 'mp:vds' 	 'mp:vgs' 	 'mp:vsb' 	 'mp:vto' 	 'mp:vts' 	 'mp:vth' 	 'mp:vgt' 	 'mp:vdss' 	 'mp:vearly' 	 'mp:lp_vfb' 	 'mp:lp_a2' 	 'mp:vbs' 	 'vbn' 	 'vbp' 	 'vdn' 	 'vdp' 	 'vgn' 	 'vgp' 	 'vx' 
Signal type: I	Data type: Real
	 'mn:1' 	 'mn:2' 	 'mn:3' 	 'mn:4' 	 'mp:1' 	 'mp:2' 	 'mp:3' 	 'mp:4' 	 'vbsn:p' 	 'vbsp:p' 	 'vdsn:p' 	 'vdsp:p' 	 'vgsn:p' 	 'vgsp:p' 	 'vnoi:p' 
Signal type: enum	Data type: Real
	 'mn:region' 	 'mp:region' 
Signal type: real	Data type: Real
	 'mn:sdint' 	 'mn:vsat' 	 'mn:u' 	 'mn:sfl' 	 'mn:sqrtsff' 	 'mn:sqrtsfw' 	 'mn:sid' 	 'mn:sig' 	 'mn:cigid' 	 'mn:noi_mid' 	 'mn:noi_mig' 	 'mn:noi_migid' 	 'mn:noi_cgeff' 	 'mn:noi_cigid' 	 'mn:fknee' 	 'mn:sigs' 	 'mn:sigd' 	 'mn:siavl' 	 'mn:ssi' 	 'mn:sdi' 	 'mn:lp_ct' 	 'mn:lp_themu' 	 'mn:lp_cs' 	 'mn:lv13' 	 'mn:lv14' 	 'mn:lp_thecs' 	 'mn:lp_ctg' 	 'mn:lp_cfac' 	 'mn:lp_axac' 	 'mn:lp_alpac' 	 'mn:lp_gc2ov' 	 'mn:lp_gc3ov' 	 'mp:sdint' 	 'mp:vsat' 	 'mp:u' 	 'mp:sfl' 	 'mp:sqrtsff' 	 'mp:sqrtsfw' 	 'mp:sid' 	 'mp:sig' 	 'mp:cigid' 	 'mp:noi_mid' 	 'mp:noi_mig' 	 'mp:noi_migid' 	 'mp:noi_cgeff' 	 'mp:noi_cigid' 	 'mp:fknee' 	 'mp:sigs' 	 'mp:sigd' 	 'mp:siavl' 	 'mp:ssi' 	 'mp:sdi' 	 'mp:lp_ct' 	 'mp:lp_themu' 	 'mp:lp_cs' 	 'mp:lv13' 	 'mp:lv14' 	 'mp:lp_thecs' 	 'mp:lp_ctg' 	 'mp:lp_cfac' 	 'mp:lp_axac' 	 'mp:lp_alpac' 	 'mp:lp_gc2ov' 	 'mp:lp_gc3ov' 
Signal type: A	Data type: Real
	 'mn:ise' 	 'mn:ige' 	 'mn:ide' 	 'mn:ibe' 	 'mn:ids' 	 'mn:idb' 	 'mn:isb' 	 'mn:igs' 	 'mn:igd' 	 'mn:igb' 	 'mn:idedge' 	 'mn:igcs' 	 'mn:igcd' 	 'mn:iavl' 	 'mn:igisl' 	 'mn:igidl' 	 'mn:ijs' 	 'mn:ijsbot' 	 'mn:ijsgat' 	 'mn:ijssti' 	 'mn:ijd' 	 'mn:ijdbot' 	 'mn:ijdgat' 	 'mn:ijdsti' 	 'mp:ise' 	 'mp:ige' 	 'mp:ide' 	 'mp:ibe' 	 'mp:ids' 	 'mp:idb' 	 'mp:isb' 	 'mp:igs' 	 'mp:igd' 	 'mp:igb' 	 'mp:idedge' 	 'mp:igcs' 	 'mp:igcd' 	 'mp:iavl' 	 'mp:igisl' 	 'mp:igidl' 	 'mp:ijs' 	 'mp:ijsbot' 	 'mp:ijsgat' 	 'mp:ijssti' 	 'mp:ijd' 	 'mp:ijdbot' 	 'mp:ijdgat' 	 'mp:ijdsti' 
Signal type: Coul	Data type: Real
	 'mn:qg' 	 'mn:qd' 	 'mn:qb' 	 'mn:qs' 	 'mn:qgs_ov' 	 'mn:qgd_ov' 	 'mn:qfgs' 	 'mn:qfgd' 	 'mn:qgb_ov' 	 'mn:qjun_s' 	 'mn:qjun_d' 	 'mp:qg' 	 'mp:qd' 	 'mp:qb' 	 'mp:qs' 	 'mp:qgs_ov' 	 'mp:qgd_ov' 	 'mp:qfgs' 	 'mp:qfgd' 	 'mp:qgb_ov' 	 'mp:qjun_s' 	 'mp:qjun_d' 
Signal type: W	Data type: Real
	 'mn:pwr' 	 'mn:pdiss' 	 'mp:pwr' 	 'mp:pdiss' 
Signal type: Ohm	Data type: Real
	 'mn:gm' 	 'mn:gmb' 	 'mn:gds' 	 'mn:gjs' 	 'mn:gjd' 	 'mp:gm' 	 'mp:gmb' 	 'mp:gds' 	 'mp:gjs' 	 'mp:gjd' 
Signal type: F	Data type: Real
	 'mn:cdd' 	 'mn:cdg' 	 'mn:cds' 	 'mn:cdb' 	 'mn:cgd' 	 'mn:cgg' 	 'mn:cgs' 	 'mn:cgb' 	 'mn:csd' 	 'mn:csg' 	 'mn:css' 	 'mn:csb' 	 'mn:cbd' 	 'mn:cbg' 	 'mn:cbs' 	 'mn:cbb' 	 'mn:cgsol' 	 'mn:cgdol' 	 'mn:cgbol' 	 'mn:cjs' 	 'mn:cjsbot' 	 'mn:cjsgat' 	 'mn:cjssti' 	 'mn:cjd' 	 'mn:cjdbot' 	 'mn:cjdgat' 	 'mn:cjdsti' 	 'mn:lv36' 	 'mn:lv37' 	 'mn:lv38' 	 'mp:cdd' 	 'mp:cdg' 	 'mp:cds' 	 'mp:cdb' 	 'mp:cgd' 	 'mp:cgg' 	 'mp:cgs' 	 'mp:cgb' 	 'mp:csd' 	 'mp:csg' 	 'mp:css' 	 'mp:csb' 	 'mp:cbd' 	 'mp:cbg' 	 'mp:cbs' 	 'mp:cbb' 	 'mp:cgsol' 	 'mp:cgdol' 	 'mp:cgbol' 	 'mp:cjs' 	 'mp:cjsbot' 	 'mp:cjsgat' 	 'mp:cjssti' 	 'mp:cjd' 	 'mp:cjdbot' 	 'mp:cjdgat' 	 'mp:cjdsti' 	 'mp:lv36' 	 'mp:lv37' 	 'mp:lv38' 
Signal type: m	Data type: Real
	 'mn:lpoly' 	 'mn:lv51' 	 'mp:lpoly' 	 'mp:lv51' 
Signal type: Ohm	Data type: Real
	 'mn:rout' 	 'mn:rg' 	 'mn:lp_rs' 	 'mp:rout' 	 'mp:rg' 	 'mp:lp_rs' 
Signal type: A_V_2	Data type: Real
	 'mn:beff' 	 'mp:beff' 
Signal type: Hz	Data type: Real
	 'mn:fug' 	 'mp:fug' 
Signal type: A_2_Hz	Data type: Real
	 'mn:sfledge' 	 'mn:sidedge' 	 'mp:sfledge' 	 'mp:sidedge' 
Signal type: m_2__V_s	Data type: Real
	 'mn:lp_betn' 	 'mp:lp_betn' 
Signal type: m_V	Data type: Real
	 'mn:lp_mue' 	 'mp:lp_mue' 
Signal type: V__1	Data type: Real
	 'mn:lp_xcor' 	 'mn:lp_thesat' 	 'mn:lp_thesatac' 	 'mp:lp_xcor' 	 'mp:lp_thesat' 	 'mp:lp_thesatac' 
Signal type: K	Data type: Real
	 'mn:dtsh' 	 'mn:tk' 	 'mp:dtsh' 	 'mp:tk' 


ans = 

  struct with fields:

    signal_info: {1×38 cell}
           prop: {40×1 cell}
              V: {31×1 cell}
              I: {15×1 cell}
           enum: {2×1 cell}
           real: {64×1 cell}
              A: {48×1 cell}
           Coul: {22×1 cell}
              W: {4×1 cell}
            Ohm: {6×1 cell}
              F: {60×1 cell}
              m: {4×1 cell}
          A_V_2: {2×1 cell}
             Hz: {2×1 cell}
         A_2_Hz: {4×1 cell}
       m_2__V_s: {2×1 cell}
            m_V: {2×1 cell}
           V__1: {6×1 cell}
              K: {4×1 cell}
What am I doing wrong?

**Comment by wgtLencha** [comment]
When I googled Cadence forum: this is what I have found this:
https://community.cadence.com/cadence_technology_forums/f/rf-design/19229/cds_srr-error
It says this error may happen with non-spectre simulation result. But mine is spectre Simulation result. And the directory name and the result database exists. I do not know how to debug this.
Did yours work?

**Comment by wgtLencha** [comment]
Also on your techSw_config_bsim3_180msrf_spectre line #120
'simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=%d tnom=27 rawfmt=psfbin rawfile="./%s" \n'...
The simulation fails to generate a netlist file and errors out but when I remove the rawfile="./%s"
The simulation works if I do this:
'simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=%d tnom=27 rawfmt=psfbin rawfile="./techsweep_120psp.raw" \n'...
or if I remove in my case rawfile = "./techsweep_12pps.raw" and remove in your case rawfile = "./%s"
'simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=%d tnom=27 rawfmt=psfbin  \n'...
Can you please double-check and let me now?

**Comment by wgtLencha** [comment]
Hello,
I compared the netlist generated through the manual ADEXL simulation and through the 
techsweep_spectre_run MATLAB script and they are the same. 
For now, I have commented the noise sections, until I get the main MATLAB script fully functional. But the major problem, I am having is that wrong data is getting generated by the Main MATLAB script.
The main Matlab script techsweep_spectre_run, generates wrong data structure for both nfet and pfet transistors. 
For comparison, I am attaching the correct data structure generated manually through the ADEXL simulation and the data structure generated through the MATLAB script file.
The first mat file is the correct one and the last two mat files are the wrong once. 
Thanks
[120pch_test.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4202762/120pch_test.txt)
[120psp_nch.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4202765/120psp_nch.txt)
[120psp_pch.txt](https://github.com/fengqzHD/gmIdNeoKit/files/4202766/120psp_pch.txt)

**Comment by wgtLencha** [comment]
Can you also do a quick test if the lookup table generated is correct?
I have done a check and found a discrepancy b/n values. 
This is what I have done:
In ADEXL I did a DC sweep of VDS from 0 to 1.2 in 25mV step and parametric sweep of VGS from 0:25e-3:1.2 and plotted ID vs VDS with 13 different VGS plots. The channel length is set to 120nm the Width 10um with 5 fingers (2um for each finger width). Likewise, the main MATLAB script was configured with the same VGS and VDS step of 25e-3. 
I am attaching the ADE XL plot generated below. Then, in ADE XL, I looked up for ID at VGS = 1 and VDS = 0.6, and captured the ID value and compared it to the result I obtained through the MATLAB script by doing in MATLAB command window:  look_up(nch, ‘ID’, ‘L’, 0.12, ‘VGS’, 1, ‘VDS’, 0.6, ‘VSB’, 0) and I get different value from what I obtained through ADE XL.

Can you also do a quick check for your technology and compare the results? 
[ID_vs_VDS.pdf](https://github.com/fengqzHD/gmIdNeoKit/files/4208809/ID_vs_VDS.pdf)

**Comment by fengqzHD** [comment]
There are too many questions asked here. I do think to ask different questions in different tickets is the better way.
I will try to answer here and close the ticket.
1) rawfile issue
As long as you can create the netlist and get the data you need, you can create the netlist in the way you like. In the netlist I created, the line is
 _simOptions options gmin=1e-13 reltol=1e-4 vabstol=1e-6 iabstol=1e-10 temp=27 tnom=27 rawfmt=    psfbin rawfile="./techsweep_130bcd.raw"_
2)  Different result
I've done a comparison of the result from Spectre through ADE and the result from the MAT file using the lookup function in LupMos.py. The average error is less than 1 %. Given that the error you mentioned are connected to the MATLAB script, sending an email to  Prof. Murmann would be a more effective way.
