### ISSUE TITLE
Adding More sections 

### ISSUE THREAD

**Issue by wgtLencha** [fengqzHD/gmIdNeoKit#5]
Hello, 
I want to characterize TSMC180nm msrf PDK. It is a single model file with multiple sections. In my code, I have provided a path for the location of model file which contains lots of sections. From these sections, I would like to use tt_rfmos, stat_noise, and tt to be able to run the simulation. 
How do I proceed with providing multiple sections for the model file?
I did wrote the first section of the code in line # 18
c.modelfile = sprintf('/grps/ef-test/TSMC180RF/TSMC_PDK/models/spectre/cr018gpii_v1d0.scs" section=tt_rfmos');
Since I only have single model file with several sections, shall write the different sections in the simulation netlist section of the code by doing include statement as shown below?

I wrote two include lines to indicate the two sections on line # 97 and #98 of my code
'include "/grps/ef-test/TSMC180RF/TSMC_PDK/models/spectre/cr018gpii_v1d0.scs" section=tt \n'...
'include "/grps/ef-test/TSMC180RF/TSMC_PDK/models/spectre/cr018gpii_v1d0.scs" section=stat_noise \n'...

After it ran successfuly
Simulation Starts for L = 0.180
Simulation Finished for L = 0.180 with VSB = 0.00 V
Info, results techsweep_180msrf.raw are changed, reloading
I get an error message that says that: 
Reference to non-existent field 'rall'.

Error in techsweep_spectre_run (line 67)
            values_n =
            struct_n.(params_n{2}); How shall I proceed with this issue?
In order to debug, I ran a simple dc sweep of a transistor to observe the existence of the parameter self_gain and confirmed that it exists. How do I resolve this issue?
I will be attaching my config and specture_run codes. 
To debug the validity of the model file and sections, I wrote a simple spectre netlist by providing

 these three sections and run successfully from the Linux command line.
Thanks a lot

**Comment by fengqzHD** [comment]
Sorry, I don't know how to debug this problem for you without running the program in your setting.

In the original gm_ID_starter_kit, there is a Matlab file with the name techsweep_spectre_debug.m. Running this first might help you to debug your problem.

**Comment by wgtLencha** [comment]
Hello,
I found the problem. The unit should be real in my environment. Thank you for pointing me to the right direction.
You can close the case now. 
Thank you so much indeed

**Comment by fengqzHD** [comment]
Great. I will close the issue.
