### ISSUE TITLE
VSB和VBS对应问题

### ISSUE THREAD

**Issue by Monkasa** [fengqzHD/gmIdNeoKit#6]
1. mat文件生成模块中，主要是config文件中的网表（netlist）中nmos 的VBS=-VSB；但pmos的VBS=VSB（可能是为了仿真方便这样设置的）。而python gui的代码中直接令VBS=-VSB(我不懂python。。。。。如果我没理解错那行代码的话)
![1](https://user-images.githubusercontent.com/49481307/82109074-fb30ec80-9765-11ea-9dc3-8b32ccfb5868.PNG)

![2](https://user-images.githubusercontent.com/49481307/82109084-113ead00-9766-11ea-923c-3a16d7017b8f.PNG)

注：也有可能是我看错了
2.python Gui的VBS不能设置成负数。。。。

**Comment by fengqzHD** [comment]
mat生成有关nmos和pmos的不同，我是直接用了Prof.Murmann的code（https://web.stanford.edu/~murmann/gmid）
<img width="692" alt="Screen Shot 2020-05-16 at 07 53 16" src="https://user-images.githubusercontent.com/33274658/82119195-8e5c2900-974a-11ea-8c8f-aca70f3a8363.png">

关于Python GUI中的处理，我需要过几天有时间时候再仔细想想为什么这么处理。让我猜，VSB或者VBS对于nmos和pmos的处理，应该都是为了不引起Source和Body间的diode导通。【原谅我中英文放一起说，因为已经不记得本科学的专业名词了】

**Comment by Monkasa** [comment]
emmm。。。我感觉一开始生成mat矩阵声明的c.VSB仅仅代表的是nmos 的source 和body的电压差，或者说是pmos的 source 和body的电压差的绝对值。
对于nmos，其由于直接做在衬底（substrate）上，body是必须接GND（所有nmos共用一个substrate），所以其vbsn<=0，在声明netlist的时候就把c.VSB直接取反了；
对于pmos，其一般做在nwell里（每个pmos都有个nwell，body不必相连），body可以和source连接在一起，或是body接VDD，所以其vbsp>=0,即如网表（netlist），vbsp=C.VSB；
另外，因为nmos与pmos呈现出一中对称关系，所以在netlist中pmos所声明的vdsp、vgsp，vgsp是nmos所声明的vdsn、vgsn，vgsn数值在前面加上负号。
我觉得看可以向Prof.Murmann工作里的lookup以及lookupvgs函数一样，直接以VSB作为函数的一个变量，与生成的mat矩阵对应（其也是用VSB作为变量）。。如果非要用VBS的话， 感觉会是个负数，这样在GUI中的self.VSB才会是正数，因为一开始生成mat矩阵所声明的c.VSB就是个正数
另外，十分感谢你的分享！

**Comment by fengqzHD** [comment]
我同意你的观点，这些也是我能想到，VSB代表的是绝对值。
netlist中，对于nmos和pmos的处理正是基于对称关系。用netflist做simulation并且产生的数据是没有问题的，不会导致substrate和source的短接。
关于GUI中对VSB或者VBS的处理，我会在下一次更新时候再梳理一下。本来这个工具是自己写着玩，自己能用就好了。现在放到了网上，应该更认真一些。
如果你使用过程中有什么反馈，或者对于这个tool的设计有什么建议，可以继续发布在github，或者给我写邮件。大概用哥大和我的姓名，就能搜索到我的邮件信息。

**Comment by fengqzHD** [comment]
我重新看了一下有如下几点，作为这个问题的总结
1. 对于nmos和pmos，常规情况下，Vsbn > 0 & Vsbp < 0。这一点在config_tech_spectre和spectre_run中是保证了的
2. GUI中，针对这一点的应该改进设置和显示。nmos时，显示Vsbn，并且限制其大于0。pmos时显示Vbsp，并且限制大于0。
3. GUI相关文件中
runGmIdSizing.py的UpdataBias
        self.VSB = -float(self.ui.spinBoxBiasVbs.value())*0.001
与LupMos.py的lookupfz
    points = ( -vsbf, vdsf, vgsf, lf)
出现了两个负号。目前来看这两个负号的作用时，当Vsb的绝对值增加时，Vth的绝对值增加，与理论相符合。

**Comment by Monkasa** [comment]
嗯嗯，我之前应该是没看到LupMos.py里面的内容，感谢你的回答

**Comment by fengqzHD** [comment]
多谢反馈
没有人提出问题，也就没有提升
